CREATE TABLE IF NOT EXISTS wp_wcfm_marketplace_orders (
    ID integer PRIMARY KEY AUTOINCREMENT,
    vendor_id bigint(20) NOT NULL DEFAULT 0,
    order_id bigint(20) NOT NULL DEFAULT 0,
    customer_id bigint(20) NOT NULL DEFAULT 0,
    payment_method varchar(255) NOT NULL DEFAULT '',
    product_id bigint(20) NOT NULL DEFAULT 0,
    variation_id bigint(20) NOT NULL DEFAULT 0,
    quantity bigint(20) NOT NULL DEFAULT 1,
    product_price decimal(19,4) NOT NULL DEFAULT 0.0000,
    total_commission decimal(19,4) NOT NULL DEFAULT 0.0000,
    commission_amount decimal(19,4) NOT NULL DEFAULT 0.0000,
    tax decimal(19,4) NOT NULL DEFAULT 0.0000,
    shipping decimal(19,4) NOT NULL DEFAULT 0.0000,
    item_id bigint(20) NOT NULL DEFAULT 0,
    shipping_tax_amount decimal(19,4) NOT NULL DEFAULT 0.0000,
    item_total decimal(19,4) NOT NULL DEFAULT 0.0000,
    item_sub_total decimal(19,4) NOT NULL DEFAULT 0.0000,
    created datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
    order_status varchar(255) NOT NULL DEFAULT '',
    commission_status varchar(255) NOT NULL DEFAULT '',
    withdraw_status varchar(255) NOT NULL DEFAULT '',
    refund_status varchar(255) NOT NULL DEFAULT '',
    is_refunded tinyint(1) NOT NULL DEFAULT 0,
    is_trashed tinyint(1) NOT NULL DEFAULT 0
);
